# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# Check the latest compatible versions at https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.2

# Fabric API
fabric_version=0.141.4+1.21.11

# Loom
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.1.5
maven_group=com.craftcloudclient.client
archives_base_name=craftcloudclient
